"""create animals table

Revision ID: 6b2ad2a3b3f3
Revises: f56de9310c32
Create Date: 2026-01-27 12:21:47.456276

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b2ad2a3b3f3"
down_revision: Union[str, None] = "f56de9310c32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animals",
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("primary_photo_url", sa.String(), nullable=True),
        sa.Column("extra_photos_url", sa.Text(), nullable=True),
        sa.Column("species", sa.Enum("DOG", "CAT", "OTHER", name="animalspecies"), nullable=False),
        sa.Column("breed", sa.String(), nullable=True),
        sa.Column("size", sa.Enum("SMALL", "MEDIUM", "LARGE", name="animalsize"), nullable=True),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("age_unit", sa.Enum("MONTHS", "YEARS", name="animalageunit"), nullable=False),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", name="animalgender"), nullable=False),
        sa.Column(
            "adoption_status",
            sa.Enum("AVAILABLE", "ADOPTED", "ON_HOLD", name="animaladoptionstatus"),
            nullable=False,
        ),
        sa.Column(
            "current_location",
            sa.Enum("FOSTERED", "SHELTER", "STRAY", name="animalcurrentlocation"),
            nullable=True,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("medical_notes", sa.Text(), nullable=True),
        sa.Column("behavioral_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("animals")
    # ### end Alembic commands ###
